services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: editra-backend
    restart: unless-stopped
    volumes:
      - ./backend/uploads:/app/uploads:Z
    expose:
      - "5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: editra-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:80"
